[package]
name = "client"
version = "0.1.0"
authors = ["sbaginsk <szymon.baginski@gmail.com>"]

[dependencies]
mio = "0.5"
json = "0.11"
base64 = "0.9"
log = "0.4"
env_logger = "0.5"
common = { path = "../common" }
console = "0.6"