[package]
name = "server"
version = "0.1.0"
authors = ["sbaginsk <szymon.baginski@gmail.com>"]

[dependencies]
mio = "0.5"
json = "0.11"
bytes = "0.3"
base64 = "0.9"
log = "0.4"
env_logger = "0.5"
common = { path = "../common" }
primes = "0.2"
rand = "0.5"
num-bigint = "0.2"
clap = "2.32"